-- Istanbul mahalle seed (961 kayıt)
-- Kaynak: https://raw.githubusercontent.com/bertugfahriozer/il_ilce_mahalle/master/il_ilce_mahalle.json
-- Üretim: scripts/build_istanbul_seed.mjs
-- Not: districts tablosu zaten seed edilmiş durumda (39 ilçe).
-- İlçe bazlı mahalle sayısı:
--   Adalar           5
--   Arnavutköy       38
--   Ataşehir         17
--   Avcılar          10
--   Bağcılar         22
--   Bahçelievler     11
--   Bakırköy         15
--   Başakşehir       10
--   Bayrampaşa       11
--   Beşiktaş         23
--   Beykoz           45
--   Beylikdüzü       10
--   Beyoğlu          45
--   Büyükçekmece     24
--   Çatalca          39
--   Çekmeköy         21
--   Esenler          17
--   Esenyurt         43
--   Eyüpsultan       29
--   Fatih            57
--   Gaziosmanpaşa    16
--   Güngören         11
--   Kadıköy          21
--   Kağıthane        19
--   Kartal           20
--   Küçükçekmece     21
--   Maltepe          18
--   Pendik           36
--   Sancaktepe       19
--   Sarıyer          38
--   Silivri          35
--   Sultanbeyli      15
--   Sultangazi       15
--   Şile             62
--   Şişli            25
--   Tuzla            17
--   Ümraniye         35
--   Üsküdar          33
--   Zeytinburnu      13
-- Ad temizliği: "Mah.", "Mahallesi", "MAH" gibi sonekler ayıklandı; büyük harfle
-- yazılmış adlar title-case'e çevrildi (Türkçe kurallarına göre). Örn:
--   "CİHANGİR Mah."  -> "Cihangir"
--   "KUZGUNCUK Mah." -> "Kuzguncuk"

insert into public.neighborhoods (district_id, name)
select d.id, v.name
from public.districts d
join (values
  ('Adalar', 'Burgazada'),
  ('Adalar', 'Heybeliada'),
  ('Adalar', 'Kınalıada'),
  ('Adalar', 'Maden'),
  ('Adalar', 'Nizam'),
  ('Arnavutköy', 'Adnan Menderes'),
  ('Arnavutköy', 'Anadolu'),
  ('Arnavutköy', 'Arnavutköy Merkez'),
  ('Arnavutköy', 'Atatürk'),
  ('Arnavutköy', 'Baklalı'),
  ('Arnavutköy', 'Balaban'),
  ('Arnavutköy', 'Boğazköy İstiklal'),
  ('Arnavutköy', 'Bolluca'),
  ('Arnavutköy', 'Boyalık'),
  ('Arnavutköy', 'Çilingir'),
  ('Arnavutköy', 'Deliklikaya'),
  ('Arnavutköy', 'Dursunköy'),
  ('Arnavutköy', 'Durusu'),
  ('Arnavutköy', 'Fatih'),
  ('Arnavutköy', 'Hacımaşlı'),
  ('Arnavutköy', 'Hadımköy'),
  ('Arnavutköy', 'Haraççı'),
  ('Arnavutköy', 'Hastane'),
  ('Arnavutköy', 'Hicret'),
  ('Arnavutköy', 'İmrahor'),
  ('Arnavutköy', 'İslambey'),
  ('Arnavutköy', 'Karaburun'),
  ('Arnavutköy', 'Karlıbayır'),
  ('Arnavutköy', 'Mareşal Fevzi Çakmak'),
  ('Arnavutköy', 'Mavigöl'),
  ('Arnavutköy', 'Mehmet Akif Ersoy'),
  ('Arnavutköy', 'Mustafa Kemal Paşa'),
  ('Arnavutköy', 'Nene Hatun'),
  ('Arnavutköy', 'Ömerli'),
  ('Arnavutköy', 'Sazlıbosna'),
  ('Arnavutköy', 'Taşoluk'),
  ('Arnavutköy', 'Tayakadın'),
  ('Arnavutköy', 'Terkos'),
  ('Arnavutköy', 'Yassıören'),
  ('Arnavutköy', 'Yavuz Selim'),
  ('Arnavutköy', 'Yeniköy'),
  ('Arnavutköy', 'Yeşilbayır'),
  ('Arnavutköy', 'Yunus Emre'),
  ('Ataşehir', 'Aşık Veysel'),
  ('Ataşehir', 'Atatürk'),
  ('Ataşehir', 'Barbaros'),
  ('Ataşehir', 'Esatpaşa'),
  ('Ataşehir', 'Ferhatpaşa'),
  ('Ataşehir', 'Fetih'),
  ('Ataşehir', 'İçerenköy'),
  ('Ataşehir', 'İnönü'),
  ('Ataşehir', 'Kayışdağı'),
  ('Ataşehir', 'Küçükbakkalköy'),
  ('Ataşehir', 'Mevlana'),
  ('Ataşehir', 'Mimar Sinan'),
  ('Ataşehir', 'Mustafa Kemal'),
  ('Ataşehir', 'Örnek'),
  ('Ataşehir', 'Yeni Çamlıca'),
  ('Ataşehir', 'Yenisahra'),
  ('Ataşehir', 'Yenişehir'),
  ('Avcılar', 'Ambarlı'),
  ('Avcılar', 'Cihangir'),
  ('Avcılar', 'Denizköşkler'),
  ('Avcılar', 'Firuzköy'),
  ('Avcılar', 'Gümüşpala'),
  ('Avcılar', 'Merkez'),
  ('Avcılar', 'Mustafa Kemal Paşa'),
  ('Avcılar', 'Tahtakale'),
  ('Avcılar', 'Üniversite'),
  ('Avcılar', 'Yeşilkent'),
  ('Bağcılar', '100. Yıl'),
  ('Bağcılar', '15 Temmuz'),
  ('Bağcılar', 'Bağlar'),
  ('Bağcılar', 'Barbaros'),
  ('Bağcılar', 'Çınar'),
  ('Bağcılar', 'Demirkapı'),
  ('Bağcılar', 'Fatih'),
  ('Bağcılar', 'Fevzi Çakmak'),
  ('Bağcılar', 'Göztepe'),
  ('Bağcılar', 'Güneşli'),
  ('Bağcılar', 'Hürriyet'),
  ('Bağcılar', 'İnönü'),
  ('Bağcılar', 'Kazım Karabekir'),
  ('Bağcılar', 'Kemalpaşa'),
  ('Bağcılar', 'Kirazlı'),
  ('Bağcılar', 'Mahmutbey'),
  ('Bağcılar', 'Merkez'),
  ('Bağcılar', 'Sancaktepe'),
  ('Bağcılar', 'Yavuz Selim'),
  ('Bağcılar', 'Yenigün'),
  ('Bağcılar', 'Yenimahalle'),
  ('Bağcılar', 'Yıldıztepe'),
  ('Bahçelievler', 'Bahçelievler'),
  ('Bahçelievler', 'Cumhuriyet'),
  ('Bahçelievler', 'Çobançeşme'),
  ('Bahçelievler', 'Fevzi Çakmak'),
  ('Bahçelievler', 'Hürriyet'),
  ('Bahçelievler', 'Kocasinan Merkez'),
  ('Bahçelievler', 'Siyavuşpaşa'),
  ('Bahçelievler', 'Soğanlı'),
  ('Bahçelievler', 'Şirinevler'),
  ('Bahçelievler', 'Yenibosna Merkez'),
  ('Bahçelievler', 'Zafer'),
  ('Bakırköy', 'Ataköy 1. Kısım'),
  ('Bakırköy', 'Ataköy 2. 5. 6. Kısım'),
  ('Bakırköy', 'Ataköy 3-4-11. Kısım'),
  ('Bakırköy', 'Ataköy 7-8-9-10. Kısım'),
  ('Bakırköy', 'Basınköy'),
  ('Bakırköy', 'Cevizlik'),
  ('Bakırköy', 'Kartaltepe'),
  ('Bakırköy', 'Osmaniye'),
  ('Bakırköy', 'Sakızağacı'),
  ('Bakırköy', 'Şenlikköy'),
  ('Bakırköy', 'Yenimahalle'),
  ('Bakırköy', 'Yeşilköy'),
  ('Bakırköy', 'Yeşilyurt'),
  ('Bakırköy', 'Zeytinlik'),
  ('Bakırköy', 'Zuhuratbaba'),
  ('Başakşehir', 'Altınşehir'),
  ('Başakşehir', 'Bahçeşehir 1. Kısım'),
  ('Başakşehir', 'Bahçeşehir 2. Kısım'),
  ('Başakşehir', 'Başak'),
  ('Başakşehir', 'Başakşehir'),
  ('Başakşehir', 'Güvercintepe'),
  ('Başakşehir', 'Kayabaşı'),
  ('Başakşehir', 'Şahintepesi'),
  ('Başakşehir', 'Şamlar'),
  ('Başakşehir', 'Ziya Gökalp'),
  ('Bayrampaşa', 'Altıntepsi'),
  ('Bayrampaşa', 'Cevatpaşa'),
  ('Bayrampaşa', 'İsmetpaşa'),
  ('Bayrampaşa', 'Kartaltepe'),
  ('Bayrampaşa', 'Kocatepe'),
  ('Bayrampaşa', 'Muratpaşa'),
  ('Bayrampaşa', 'Orta'),
  ('Bayrampaşa', 'Terazidere'),
  ('Bayrampaşa', 'Vatan'),
  ('Bayrampaşa', 'Yenidoğan'),
  ('Bayrampaşa', 'Yıldırım'),
  ('Beşiktaş', 'Abbasağa'),
  ('Beşiktaş', 'Akat'),
  ('Beşiktaş', 'Arnavutköy'),
  ('Beşiktaş', 'Balmumcu'),
  ('Beşiktaş', 'Bebek'),
  ('Beşiktaş', 'Cihannüma'),
  ('Beşiktaş', 'Dikilitaş'),
  ('Beşiktaş', 'Etiler'),
  ('Beşiktaş', 'Gayrettepe'),
  ('Beşiktaş', 'Konaklar'),
  ('Beşiktaş', 'Kuruçeşme'),
  ('Beşiktaş', 'Kültür'),
  ('Beşiktaş', 'Levazım'),
  ('Beşiktaş', 'Levent'),
  ('Beşiktaş', 'Mecidiye'),
  ('Beşiktaş', 'Muradiye'),
  ('Beşiktaş', 'Nisbetiye'),
  ('Beşiktaş', 'Ortaköy'),
  ('Beşiktaş', 'Sinanpaşa'),
  ('Beşiktaş', 'Türkali'),
  ('Beşiktaş', 'Ulus'),
  ('Beşiktaş', 'Vişnezade'),
  ('Beşiktaş', 'Yıldız'),
  ('Beykoz', 'Acarlar'),
  ('Beykoz', 'Akbaba'),
  ('Beykoz', 'Alibahadır'),
  ('Beykoz', 'Anadolu Hisarı'),
  ('Beykoz', 'Anadolu Kavağı'),
  ('Beykoz', 'Anadolufeneri'),
  ('Beykoz', 'Baklacı'),
  ('Beykoz', 'Beykoz Merkez'),
  ('Beykoz', 'Bozhane'),
  ('Beykoz', 'Cumhuriyet'),
  ('Beykoz', 'Çamlıbahçe'),
  ('Beykoz', 'Çengeldere'),
  ('Beykoz', 'Çiftlik'),
  ('Beykoz', 'Çiğdem'),
  ('Beykoz', 'Çubuklu'),
  ('Beykoz', 'Dereseki'),
  ('Beykoz', 'Elmalı'),
  ('Beykoz', 'Fatih'),
  ('Beykoz', 'Göksu'),
  ('Beykoz', 'Göllü'),
  ('Beykoz', 'Görele'),
  ('Beykoz', 'Göztepe'),
  ('Beykoz', 'Gümüşsuyu'),
  ('Beykoz', 'İncirköy'),
  ('Beykoz', 'İshaklı'),
  ('Beykoz', 'Kanlıca'),
  ('Beykoz', 'Kavacık'),
  ('Beykoz', 'Kaynarca'),
  ('Beykoz', 'Kılıçlı'),
  ('Beykoz', 'Mahmutşevketpaşa'),
  ('Beykoz', 'Ortaçeşme'),
  ('Beykoz', 'Öğümce'),
  ('Beykoz', 'Örnekköy'),
  ('Beykoz', 'Paşabahçe'),
  ('Beykoz', 'Paşamandıra'),
  ('Beykoz', 'Polonezköy'),
  ('Beykoz', 'Poyrazköy'),
  ('Beykoz', 'Riva'),
  ('Beykoz', 'Rüzgarlıbahçe'),
  ('Beykoz', 'Soğuksu'),
  ('Beykoz', 'Tokatköy'),
  ('Beykoz', 'Yalıköy'),
  ('Beykoz', 'Yavuz Selim'),
  ('Beykoz', 'Yeni Mahalle'),
  ('Beykoz', 'Zerzavatçı'),
  ('Beylikdüzü', 'Adnan Kahveci'),
  ('Beylikdüzü', 'Barış'),
  ('Beylikdüzü', 'Büyükşehir'),
  ('Beylikdüzü', 'Cumhuriyet'),
  ('Beylikdüzü', 'Dereağzı'),
  ('Beylikdüzü', 'Gürpınar'),
  ('Beylikdüzü', 'Kavaklı'),
  ('Beylikdüzü', 'Marmara'),
  ('Beylikdüzü', 'Sahil'),
  ('Beylikdüzü', 'Yakuplu'),
  ('Beyoğlu', 'Arap Cami'),
  ('Beyoğlu', 'Asmalı Mescit'),
  ('Beyoğlu', 'Bedrettin'),
  ('Beyoğlu', 'Bereketzade'),
  ('Beyoğlu', 'Bostan'),
  ('Beyoğlu', 'Bülbül'),
  ('Beyoğlu', 'Camiikebir'),
  ('Beyoğlu', 'Cihangir'),
  ('Beyoğlu', 'Çatma Mescit'),
  ('Beyoğlu', 'Çukur'),
  ('Beyoğlu', 'Emekyemez'),
  ('Beyoğlu', 'Evliya Çelebi'),
  ('Beyoğlu', 'Fetihtepe'),
  ('Beyoğlu', 'Firüzağa'),
  ('Beyoğlu', 'Gümüşsuyu'),
  ('Beyoğlu', 'Hacıahmet'),
  ('Beyoğlu', 'Hacımimi'),
  ('Beyoğlu', 'Halıcıoğlu'),
  ('Beyoğlu', 'Hüseyinağa'),
  ('Beyoğlu', 'İstiklal'),
  ('Beyoğlu', 'Kadımehmet Efendi'),
  ('Beyoğlu', 'Kalyoncukulluk'),
  ('Beyoğlu', 'Kamerhatun'),
  ('Beyoğlu', 'Kaptanpaşa'),
  ('Beyoğlu', 'Katipmustafa Çelebi'),
  ('Beyoğlu', 'Keçeçipiri'),
  ('Beyoğlu', 'Kemankeş Karamustafapaşa'),
  ('Beyoğlu', 'Kılıçali Paşa'),
  ('Beyoğlu', 'Kocatepe'),
  ('Beyoğlu', 'Kulaksız'),
  ('Beyoğlu', 'Kuloğlu'),
  ('Beyoğlu', 'Küçük Piyale'),
  ('Beyoğlu', 'Müeyyetzade'),
  ('Beyoğlu', 'Ömer Avni'),
  ('Beyoğlu', 'Örnektepe'),
  ('Beyoğlu', 'Piri Mehmet Paşa'),
  ('Beyoğlu', 'Piyalepaşa'),
  ('Beyoğlu', 'Pürtelaş Hasan Efendi'),
  ('Beyoğlu', 'Sururi'),
  ('Beyoğlu', 'Sütlüce'),
  ('Beyoğlu', 'Şahkulu'),
  ('Beyoğlu', 'Şehit Muhtar'),
  ('Beyoğlu', 'Tomtom'),
  ('Beyoğlu', 'Yahya Kahya'),
  ('Beyoğlu', 'Yenişehir'),
  ('Büyükçekmece', '19 Mayıs'),
  ('Büyükçekmece', 'Ahmediye'),
  ('Büyükçekmece', 'Alkent 2000'),
  ('Büyükçekmece', 'Atatürk'),
  ('Büyükçekmece', 'Bahçelievler'),
  ('Büyükçekmece', 'Celaliye'),
  ('Büyükçekmece', 'Cumhuriyet'),
  ('Büyükçekmece', 'Çakmaklı'),
  ('Büyükçekmece', 'Dizdariye'),
  ('Büyükçekmece', 'Ekinoba'),
  ('Büyükçekmece', 'Fatih'),
  ('Büyükçekmece', 'Güzelce'),
  ('Büyükçekmece', 'Hürriyet'),
  ('Büyükçekmece', 'Kamiloba'),
  ('Büyükçekmece', 'Karaağaç'),
  ('Büyükçekmece', 'Kumburgaz'),
  ('Büyükçekmece', 'Mimaroba'),
  ('Büyükçekmece', 'Mimarsinan'),
  ('Büyükçekmece', 'Murat Çesme'),
  ('Büyükçekmece', 'Pınartepe'),
  ('Büyükçekmece', 'Sinanoba'),
  ('Büyükçekmece', 'Türkoba'),
  ('Büyükçekmece', 'Ulus'),
  ('Büyükçekmece', 'Yenimahalle'),
  ('Çatalca', 'Akalan'),
  ('Çatalca', 'Atatürk'),
  ('Çatalca', 'Aydınlar'),
  ('Çatalca', 'Bahşayiş'),
  ('Çatalca', 'Başak'),
  ('Çatalca', 'Belgrat'),
  ('Çatalca', 'Celepköy'),
  ('Çatalca', 'Çakıl'),
  ('Çatalca', 'Çanakça'),
  ('Çatalca', 'Çiftlikköy'),
  ('Çatalca', 'Dağyenice'),
  ('Çatalca', 'Elbasan'),
  ('Çatalca', 'Fatih'),
  ('Çatalca', 'Ferhatpaşa'),
  ('Çatalca', 'Gökçeali'),
  ('Çatalca', 'Gümüşpınar'),
  ('Çatalca', 'Hallaçlı'),
  ('Çatalca', 'Hisarbeyli'),
  ('Çatalca', 'İhsaniye'),
  ('Çatalca', 'İnceğiz'),
  ('Çatalca', 'İzzettin'),
  ('Çatalca', 'Kabakça'),
  ('Çatalca', 'Kaleiçi'),
  ('Çatalca', 'Kalfa'),
  ('Çatalca', 'Karacaköy Merkez'),
  ('Çatalca', 'Karamandere'),
  ('Çatalca', 'Kestanelik'),
  ('Çatalca', 'Kızılcaali'),
  ('Çatalca', 'Muratbey Merkez'),
  ('Çatalca', 'Nakkaş'),
  ('Çatalca', 'Oklalı'),
  ('Çatalca', 'Ormanlı'),
  ('Çatalca', 'Ovayenice'),
  ('Çatalca', 'Örcünlü'),
  ('Çatalca', 'Örencik'),
  ('Çatalca', 'Subaşı'),
  ('Çatalca', 'Yalıköy'),
  ('Çatalca', 'Yaylacık'),
  ('Çatalca', 'Yazlık'),
  ('Çekmeköy', 'Alemdağ'),
  ('Çekmeköy', 'Aydınlar'),
  ('Çekmeköy', 'Cumhuriyet'),
  ('Çekmeköy', 'Çamlık'),
  ('Çekmeköy', 'Çatalmeşe'),
  ('Çekmeköy', 'Ekşioğlu'),
  ('Çekmeköy', 'Güngören'),
  ('Çekmeköy', 'Hamidiye'),
  ('Çekmeköy', 'Hüseyinli'),
  ('Çekmeköy', 'Kirazlıdere'),
  ('Çekmeköy', 'Koçullu'),
  ('Çekmeköy', 'Mehmet Akif'),
  ('Çekmeköy', 'Merkez'),
  ('Çekmeköy', 'Mimar Sinan'),
  ('Çekmeköy', 'Nişantepe'),
  ('Çekmeköy', 'Ömerli'),
  ('Çekmeköy', 'Reşadiye'),
  ('Çekmeköy', 'Sırapınar'),
  ('Çekmeköy', 'Soğukpınar'),
  ('Çekmeköy', 'Sultançiftliği'),
  ('Çekmeköy', 'Taşdelen'),
  ('Esenler', '15 Temmuz'),
  ('Esenler', 'Atışalanı'),
  ('Esenler', 'Birlik'),
  ('Esenler', 'Çifte Havuzlar'),
  ('Esenler', 'Davutpaşa'),
  ('Esenler', 'Fatih'),
  ('Esenler', 'Fevzi Çakmak'),
  ('Esenler', 'Kazım Karabekir'),
  ('Esenler', 'Kemer'),
  ('Esenler', 'Menderes'),
  ('Esenler', 'Mimar Sinan'),
  ('Esenler', 'Namık Kemal'),
  ('Esenler', 'Nine Hatun'),
  ('Esenler', 'Oruçreis'),
  ('Esenler', 'Tuna'),
  ('Esenler', 'Turgut Reis'),
  ('Esenler', 'Yavuz Selim'),
  ('Esenyurt', 'Akçaburgaz'),
  ('Esenyurt', 'Akevler'),
  ('Esenyurt', 'Akşemseddin'),
  ('Esenyurt', 'Ardıçlı'),
  ('Esenyurt', 'Aşık Veysel'),
  ('Esenyurt', 'Atatürk'),
  ('Esenyurt', 'Balıkyolu'),
  ('Esenyurt', 'Barbaros Hayrettin Paşa'),
  ('Esenyurt', 'Battalgazi'),
  ('Esenyurt', 'Cumhuriyet'),
  ('Esenyurt', 'Çınar'),
  ('Esenyurt', 'Esenkent'),
  ('Esenyurt', 'Fatih'),
  ('Esenyurt', 'Gökevler'),
  ('Esenyurt', 'Güzelyurt'),
  ('Esenyurt', 'Hürriyet'),
  ('Esenyurt', 'İncirtepe'),
  ('Esenyurt', 'İnönü'),
  ('Esenyurt', 'İstiklal'),
  ('Esenyurt', 'Koza'),
  ('Esenyurt', 'Mehmet Akif Ersoy'),
  ('Esenyurt', 'Mehterçeşme'),
  ('Esenyurt', 'Merkez'),
  ('Esenyurt', 'Mevlana'),
  ('Esenyurt', 'Namık Kemal'),
  ('Esenyurt', 'Necip Fazıl Kısakürek'),
  ('Esenyurt', 'Orhan Gazi'),
  ('Esenyurt', 'Osmangazi'),
  ('Esenyurt', 'Örnek'),
  ('Esenyurt', 'Pınar'),
  ('Esenyurt', 'Piri Reis'),
  ('Esenyurt', 'Saadetdere'),
  ('Esenyurt', 'Selahaddin Eyyubi'),
  ('Esenyurt', 'Sultaniye'),
  ('Esenyurt', 'Süleymaniye'),
  ('Esenyurt', 'Şehitler'),
  ('Esenyurt', 'Talatpaşa'),
  ('Esenyurt', 'Turgut Özal'),
  ('Esenyurt', 'Üçevler'),
  ('Esenyurt', 'Yenikent'),
  ('Esenyurt', 'Yeşilkent'),
  ('Esenyurt', 'Yunus Emre'),
  ('Esenyurt', 'Zafer'),
  ('Eyüpsultan', '5. Levent'),
  ('Eyüpsultan', 'Ağaçlı'),
  ('Eyüpsultan', 'Akpınar'),
  ('Eyüpsultan', 'Akşemsettin'),
  ('Eyüpsultan', 'Alibeyköy'),
  ('Eyüpsultan', 'Çırçır'),
  ('Eyüpsultan', 'Çiftalan'),
  ('Eyüpsultan', 'Defterdar'),
  ('Eyüpsultan', 'Düğmeciler'),
  ('Eyüpsultan', 'Emniyettepe'),
  ('Eyüpsultan', 'Esentepe'),
  ('Eyüpsultan', 'Eyüp Merkez'),
  ('Eyüpsultan', 'Göktürk Merkez'),
  ('Eyüpsultan', 'Güzeltepe'),
  ('Eyüpsultan', 'Işıklar'),
  ('Eyüpsultan', 'İhsaniye'),
  ('Eyüpsultan', 'İslambey'),
  ('Eyüpsultan', 'Karadolap'),
  ('Eyüpsultan', 'Mimar Sinan'),
  ('Eyüpsultan', 'Mithatpaşa'),
  ('Eyüpsultan', 'Nişanca'),
  ('Eyüpsultan', 'Odayeri'),
  ('Eyüpsultan', 'Pirinççi'),
  ('Eyüpsultan', 'Rami Cuma'),
  ('Eyüpsultan', 'Rami Yeni'),
  ('Eyüpsultan', 'Sakarya'),
  ('Eyüpsultan', 'Silahtarağa'),
  ('Eyüpsultan', 'Topçular'),
  ('Eyüpsultan', 'Yeşilpınar'),
  ('Fatih', 'Aksaray'),
  ('Fatih', 'Akşemsettin'),
  ('Fatih', 'Alemdar'),
  ('Fatih', 'Ali Kuşçu'),
  ('Fatih', 'Atikali'),
  ('Fatih', 'Ayvansaray'),
  ('Fatih', 'Balabanağa'),
  ('Fatih', 'Balat'),
  ('Fatih', 'Beyazıt'),
  ('Fatih', 'Binbirdirek'),
  ('Fatih', 'Cankurtaran'),
  ('Fatih', 'Cerrahpaşa'),
  ('Fatih', 'Cibali'),
  ('Fatih', 'Demirtaş'),
  ('Fatih', 'Derviş Ali'),
  ('Fatih', 'Emin Sinan'),
  ('Fatih', 'Hacı Kadın'),
  ('Fatih', 'Haseki Sultan'),
  ('Fatih', 'Hırka-İ Şerif'),
  ('Fatih', 'Hobyar'),
  ('Fatih', 'Hoca Gıyasettin'),
  ('Fatih', 'Hocapaşa'),
  ('Fatih', 'İskenderpaşa'),
  ('Fatih', 'Kalenderhane'),
  ('Fatih', 'Karagümrük'),
  ('Fatih', 'Katip Kasım'),
  ('Fatih', 'Kemalpaşa'),
  ('Fatih', 'Koca Mustafapaşa'),
  ('Fatih', 'Küçük Ayasofya'),
  ('Fatih', 'Mercan'),
  ('Fatih', 'Mesihpaşa'),
  ('Fatih', 'Mevlanakapı'),
  ('Fatih', 'Mimar Hayrettin'),
  ('Fatih', 'Mimar Kemalettin'),
  ('Fatih', 'Molla Fenari'),
  ('Fatih', 'Molla Gürani'),
  ('Fatih', 'Molla Hüsrev'),
  ('Fatih', 'Muhsine Hatun'),
  ('Fatih', 'Nişanca'),
  ('Fatih', 'Rüstempaşa'),
  ('Fatih', 'Saraç İshak'),
  ('Fatih', 'Sarıdemir'),
  ('Fatih', 'Seyyid Ömer'),
  ('Fatih', 'Silivrikapı'),
  ('Fatih', 'Sultan Ahmet'),
  ('Fatih', 'Sururi'),
  ('Fatih', 'Süleymaniye'),
  ('Fatih', 'Sümbül Efendi'),
  ('Fatih', 'Şehremini'),
  ('Fatih', 'Şehsuvar Bey'),
  ('Fatih', 'Tahtakale'),
  ('Fatih', 'Taya Hatun'),
  ('Fatih', 'Topkapı'),
  ('Fatih', 'Yavuz Sinan'),
  ('Fatih', 'Yavuz Sultan Selim'),
  ('Fatih', 'Yedikule'),
  ('Fatih', 'Zeyrek'),
  ('Gaziosmanpaşa', 'Bağlarbaşı'),
  ('Gaziosmanpaşa', 'Barbaros Hayrettin Paşa'),
  ('Gaziosmanpaşa', 'Fevzi Çakmak'),
  ('Gaziosmanpaşa', 'Hürriyet'),
  ('Gaziosmanpaşa', 'Karadeniz'),
  ('Gaziosmanpaşa', 'Karayolları'),
  ('Gaziosmanpaşa', 'Karlıtepe'),
  ('Gaziosmanpaşa', 'Kazım Karabekir'),
  ('Gaziosmanpaşa', 'Merkez'),
  ('Gaziosmanpaşa', 'Mevlana'),
  ('Gaziosmanpaşa', 'Pazariçi'),
  ('Gaziosmanpaşa', 'Sarıgöl'),
  ('Gaziosmanpaşa', 'Şemsipaşa'),
  ('Gaziosmanpaşa', 'Yeni Mahalle'),
  ('Gaziosmanpaşa', 'Yenidoğan'),
  ('Gaziosmanpaşa', 'Yıldıztabya'),
  ('Güngören', 'Abdurrahman Nafiz Gürman'),
  ('Güngören', 'Akıncılar'),
  ('Güngören', 'Gençosman'),
  ('Güngören', 'Güneştepe'),
  ('Güngören', 'Güven'),
  ('Güngören', 'Haznedar'),
  ('Güngören', 'Mareşal Çakmak'),
  ('Güngören', 'Mehmet Nesih Özmen'),
  ('Güngören', 'Merkez'),
  ('Güngören', 'Sanayi'),
  ('Güngören', 'Tozkoparan'),
  ('Kadıköy', '19 Mayıs'),
  ('Kadıköy', 'Acıbadem'),
  ('Kadıköy', 'Bostancı'),
  ('Kadıköy', 'Caddebostan'),
  ('Kadıköy', 'Caferağa'),
  ('Kadıköy', 'Dumlupınar'),
  ('Kadıköy', 'Eğitim'),
  ('Kadıköy', 'Erenköy'),
  ('Kadıköy', 'Fenerbahçe'),
  ('Kadıköy', 'Feneryolu'),
  ('Kadıköy', 'Fikirtepe'),
  ('Kadıköy', 'Göztepe'),
  ('Kadıköy', 'Hasanpaşa'),
  ('Kadıköy', 'Koşuyolu'),
  ('Kadıköy', 'Kozyatağı'),
  ('Kadıköy', 'Merdivenköy'),
  ('Kadıköy', 'Osmanağa'),
  ('Kadıköy', 'Rasimpaşa'),
  ('Kadıköy', 'Sahrayıcedit'),
  ('Kadıköy', 'Suadiye'),
  ('Kadıköy', 'Zühtüpaşa'),
  ('Kağıthane', 'Çağlayan'),
  ('Kağıthane', 'Çeliktepe'),
  ('Kağıthane', 'Emniyet Evleri'),
  ('Kağıthane', 'Gültepe'),
  ('Kağıthane', 'Gürsel'),
  ('Kağıthane', 'Hamidiye'),
  ('Kağıthane', 'Harmantepe'),
  ('Kağıthane', 'Hürriyet'),
  ('Kağıthane', 'Mehmet Akif Ersoy'),
  ('Kağıthane', 'Merkez'),
  ('Kağıthane', 'Nurtepe'),
  ('Kağıthane', 'Ortabayır'),
  ('Kağıthane', 'Seyrantepe'),
  ('Kağıthane', 'Sultan Selim'),
  ('Kağıthane', 'Şirintepe'),
  ('Kağıthane', 'Talatpaşa'),
  ('Kağıthane', 'Telsizler'),
  ('Kağıthane', 'Yahya Kemal'),
  ('Kağıthane', 'Yeşilce'),
  ('Kartal', 'Atalar'),
  ('Kartal', 'Cevizli'),
  ('Kartal', 'Cumhuriyet'),
  ('Kartal', 'Çavuşoğlu'),
  ('Kartal', 'Esentepe'),
  ('Kartal', 'Gümüşpınar'),
  ('Kartal', 'Hürriyet'),
  ('Kartal', 'Karlıktepe'),
  ('Kartal', 'Kordonboyu'),
  ('Kartal', 'Orhantepe'),
  ('Kartal', 'Orta'),
  ('Kartal', 'Petrol İş'),
  ('Kartal', 'Soğanlık Yeni'),
  ('Kartal', 'Topselvi'),
  ('Kartal', 'Uğur Mumcu'),
  ('Kartal', 'Yakacık Çarşı'),
  ('Kartal', 'Yakacık Yeni'),
  ('Kartal', 'Yalı'),
  ('Kartal', 'Yukarı'),
  ('Kartal', 'Yunus'),
  ('Küçükçekmece', 'Atakent'),
  ('Küçükçekmece', 'Atatürk'),
  ('Küçükçekmece', 'Beşyol'),
  ('Küçükçekmece', 'Cennet'),
  ('Küçükçekmece', 'Cumhuriyet'),
  ('Küçükçekmece', 'Fatih'),
  ('Küçükçekmece', 'Fevzi Çakmak'),
  ('Küçükçekmece', 'Gültepe'),
  ('Küçükçekmece', 'Halkalı Merkez'),
  ('Küçükçekmece', 'İnönü'),
  ('Küçükçekmece', 'İstasyon'),
  ('Küçükçekmece', 'Kanarya'),
  ('Küçükçekmece', 'Kartaltepe'),
  ('Küçükçekmece', 'Kemalpaşa'),
  ('Küçükçekmece', 'Mehmet Akif'),
  ('Küçükçekmece', 'Söğütlü Çeşme'),
  ('Küçükçekmece', 'Sultan Murat'),
  ('Küçükçekmece', 'Tevfikbey'),
  ('Küçükçekmece', 'Yarımburgaz'),
  ('Küçükçekmece', 'Yeni Mahalle'),
  ('Küçükçekmece', 'Yeşilova'),
  ('Maltepe', 'Altayçeşme'),
  ('Maltepe', 'Altıntepe'),
  ('Maltepe', 'Aydınevler'),
  ('Maltepe', 'Bağlarbaşı'),
  ('Maltepe', 'Başıbüyük'),
  ('Maltepe', 'Büyükbakkalköy'),
  ('Maltepe', 'Cevizli'),
  ('Maltepe', 'Çınar'),
  ('Maltepe', 'Esenkent'),
  ('Maltepe', 'Feyzullah'),
  ('Maltepe', 'Fındıklı'),
  ('Maltepe', 'Girne'),
  ('Maltepe', 'Gülensu'),
  ('Maltepe', 'Gülsuyu'),
  ('Maltepe', 'İdealtepe'),
  ('Maltepe', 'Küçükyalı Merkez'),
  ('Maltepe', 'Yalı'),
  ('Maltepe', 'Zümrütevler'),
  ('Pendik', 'Ahmet Yesevi'),
  ('Pendik', 'Bahçelievler'),
  ('Pendik', 'Ballıca'),
  ('Pendik', 'Batı'),
  ('Pendik', 'Çamçeşme'),
  ('Pendik', 'Çamlık'),
  ('Pendik', 'Çınardere'),
  ('Pendik', 'Doğu'),
  ('Pendik', 'Dumlupınar'),
  ('Pendik', 'Emirli'),
  ('Pendik', 'Ertuğrul Gazi'),
  ('Pendik', 'Esenler'),
  ('Pendik', 'Esenyalı'),
  ('Pendik', 'Fatih'),
  ('Pendik', 'Fevzi Çakmak'),
  ('Pendik', 'Göçbeyli'),
  ('Pendik', 'Güllü Bağlar'),
  ('Pendik', 'Güzelyalı'),
  ('Pendik', 'Harmandere'),
  ('Pendik', 'Kavakpınar'),
  ('Pendik', 'Kaynarca'),
  ('Pendik', 'Kurna'),
  ('Pendik', 'Kurtdoğmuş'),
  ('Pendik', 'Kurtköy'),
  ('Pendik', 'Orhangazi'),
  ('Pendik', 'Orta'),
  ('Pendik', 'Ramazanoğlu'),
  ('Pendik', 'Sanayi'),
  ('Pendik', 'Sapan Bağları'),
  ('Pendik', 'Sülüntepe'),
  ('Pendik', 'Şeyhli'),
  ('Pendik', 'Velibaba'),
  ('Pendik', 'Yayalar'),
  ('Pendik', 'Yeni'),
  ('Pendik', 'Yenişehir'),
  ('Pendik', 'Yeşilbağlar'),
  ('Sancaktepe', 'Abdurrahmangazi'),
  ('Sancaktepe', 'Akpınar'),
  ('Sancaktepe', 'Atatürk'),
  ('Sancaktepe', 'Emek'),
  ('Sancaktepe', 'Eyüp Sultan'),
  ('Sancaktepe', 'Fatih'),
  ('Sancaktepe', 'Hilal'),
  ('Sancaktepe', 'İnönü'),
  ('Sancaktepe', 'Kemal Türkler'),
  ('Sancaktepe', 'Meclis'),
  ('Sancaktepe', 'Merve'),
  ('Sancaktepe', 'Mevlana'),
  ('Sancaktepe', 'Osmangazi'),
  ('Sancaktepe', 'Paşaköy'),
  ('Sancaktepe', 'Safa'),
  ('Sancaktepe', 'Sarıgazi'),
  ('Sancaktepe', 'Veysel Karani'),
  ('Sancaktepe', 'Yenidoğan'),
  ('Sancaktepe', 'Yunus Emre'),
  ('Sarıyer', 'Ayazağa'),
  ('Sarıyer', 'Bahçeköy Kemer'),
  ('Sarıyer', 'Bahçeköy Merkez'),
  ('Sarıyer', 'Bahçeköy Yeni'),
  ('Sarıyer', 'Baltalimanı'),
  ('Sarıyer', 'Büyükdere'),
  ('Sarıyer', 'Cumhuriyet'),
  ('Sarıyer', 'Çamlıtepe'),
  ('Sarıyer', 'Çayırbaşı'),
  ('Sarıyer', 'Darüşşafaka'),
  ('Sarıyer', 'Demirciköy'),
  ('Sarıyer', 'Emirgan'),
  ('Sarıyer', 'Fatih Sultan Mehmet'),
  ('Sarıyer', 'Ferahevler'),
  ('Sarıyer', 'Garipçe'),
  ('Sarıyer', 'Gümüşdere'),
  ('Sarıyer', 'Huzur'),
  ('Sarıyer', 'İstinye'),
  ('Sarıyer', 'Kazım Karabekir Paşa'),
  ('Sarıyer', 'Kısırkaya'),
  ('Sarıyer', 'Kireçburnu'),
  ('Sarıyer', 'Kocataş'),
  ('Sarıyer', 'Kumköy (Kilyos)'),
  ('Sarıyer', 'Maden'),
  ('Sarıyer', 'Maslak'),
  ('Sarıyer', 'Pınar'),
  ('Sarıyer', 'Poligon'),
  ('Sarıyer', 'Ptt Evleri'),
  ('Sarıyer', 'Reşitpaşa'),
  ('Sarıyer', 'Rumelifeneri'),
  ('Sarıyer', 'Rumelihisarı'),
  ('Sarıyer', 'Rumelikavağı'),
  ('Sarıyer', 'Sarıyer'),
  ('Sarıyer', 'Tarabya'),
  ('Sarıyer', 'Uskumruköy'),
  ('Sarıyer', 'Yeni'),
  ('Sarıyer', 'Yeniköy'),
  ('Sarıyer', 'Zekeriyaköy'),
  ('Silivri', 'Akören'),
  ('Silivri', 'Alibey'),
  ('Silivri', 'Alipaşa'),
  ('Silivri', 'Bekirli'),
  ('Silivri', 'Beyciler'),
  ('Silivri', 'Büyük Çavuşlu'),
  ('Silivri', 'Büyük Kılıçlı'),
  ('Silivri', 'Büyük Sinekli'),
  ('Silivri', 'Cumhuriyet'),
  ('Silivri', 'Çanta Balaban'),
  ('Silivri', 'Çanta Sancaktepe'),
  ('Silivri', 'Çayırdere'),
  ('Silivri', 'Çeltik'),
  ('Silivri', 'Danamandıra'),
  ('Silivri', 'Değirmenköy İsmetpaşa'),
  ('Silivri', 'Değitmenköy Fevzipaşa'),
  ('Silivri', 'Fatih'),
  ('Silivri', 'Fener'),
  ('Silivri', 'Gazitepe'),
  ('Silivri', 'Gümüşyaka'),
  ('Silivri', 'Kadıköy'),
  ('Silivri', 'Kavaklı'),
  ('Silivri', 'Kavaklı İstiklal'),
  ('Silivri', 'Kurfallı'),
  ('Silivri', 'Küçük Kılıçlı'),
  ('Silivri', 'Küçük Sinekli'),
  ('Silivri', 'Mimar Sinan'),
  ('Silivri', 'Ortaköy'),
  ('Silivri', 'Piri Mehmet Paşa'),
  ('Silivri', 'Sayalar'),
  ('Silivri', 'Selimpaşa'),
  ('Silivri', 'Semizkumlar'),
  ('Silivri', 'Seymen'),
  ('Silivri', 'Yeni'),
  ('Silivri', 'Yolçatı'),
  ('Sultanbeyli', 'Abdurrahmangazi'),
  ('Sultanbeyli', 'Adil'),
  ('Sultanbeyli', 'Ahmet Yesevi'),
  ('Sultanbeyli', 'Akşemseddin'),
  ('Sultanbeyli', 'Battalgazi'),
  ('Sultanbeyli', 'Fatih'),
  ('Sultanbeyli', 'Hamidiye'),
  ('Sultanbeyli', 'Hasanpaşa'),
  ('Sultanbeyli', 'Mecidiye'),
  ('Sultanbeyli', 'Mehmet Akif'),
  ('Sultanbeyli', 'Mimar Sinan'),
  ('Sultanbeyli', 'Necip Fazıl'),
  ('Sultanbeyli', 'Orhan Gazi'),
  ('Sultanbeyli', 'Turgut Reis'),
  ('Sultanbeyli', 'Yavuz Selim'),
  ('Sultangazi', '50. Yıl'),
  ('Sultangazi', '75. Yıl'),
  ('Sultangazi', 'Cebeci'),
  ('Sultangazi', 'Cumhuriyet'),
  ('Sultangazi', 'Esentepe'),
  ('Sultangazi', 'Eski Habipler'),
  ('Sultangazi', 'Gazi'),
  ('Sultangazi', 'Habibler'),
  ('Sultangazi', 'İsmet Paşa'),
  ('Sultangazi', 'Malkoçoğlu'),
  ('Sultangazi', 'Sultançiftliği'),
  ('Sultangazi', 'Uğur Mumcu'),
  ('Sultangazi', 'Yayla'),
  ('Sultangazi', 'Yunus Emre'),
  ('Sultangazi', 'Zübeyde Hanım'),
  ('Şile', 'Ağaçdere'),
  ('Şile', 'Ağva Merkez'),
  ('Şile', 'Ahmetli'),
  ('Şile', 'Akçakese'),
  ('Şile', 'Alacalı'),
  ('Şile', 'Avcıkoru'),
  ('Şile', 'Balibey'),
  ('Şile', 'Bıçkıdere'),
  ('Şile', 'Bozgoca'),
  ('Şile', 'Bucaklı'),
  ('Şile', 'Çataklı'),
  ('Şile', 'Çavuş'),
  ('Şile', 'Çayırbaşı'),
  ('Şile', 'Çelebi'),
  ('Şile', 'Çengilli'),
  ('Şile', 'Darlık'),
  ('Şile', 'Değirmençayırı'),
  ('Şile', 'Doğancılı'),
  ('Şile', 'Erenler'),
  ('Şile', 'Esenceli'),
  ('Şile', 'Geredeli'),
  ('Şile', 'Göçe'),
  ('Şile', 'Gökmaşlı'),
  ('Şile', 'Göksu'),
  ('Şile', 'Hacı Kasım'),
  ('Şile', 'Hacıllı'),
  ('Şile', 'Hasanlı'),
  ('Şile', 'İmrendere'),
  ('Şile', 'İmrenli'),
  ('Şile', 'İsaköy'),
  ('Şile', 'Kabakoz'),
  ('Şile', 'Kadıköy'),
  ('Şile', 'Kalem'),
  ('Şile', 'Karabeyli'),
  ('Şile', 'Karacaköy'),
  ('Şile', 'Karakiraz'),
  ('Şile', 'Karamandere'),
  ('Şile', 'Kervansaray'),
  ('Şile', 'Kızılca'),
  ('Şile', 'Korucu'),
  ('Şile', 'Kömürlük'),
  ('Şile', 'Kumbaba'),
  ('Şile', 'Kurfallı'),
  ('Şile', 'Kurna'),
  ('Şile', 'Meşrutiyet'),
  ('Şile', 'Oruçoğlu'),
  ('Şile', 'Osmanköy'),
  ('Şile', 'Ovacık'),
  ('Şile', 'Sahilköy'),
  ('Şile', 'Satmazlı'),
  ('Şile', 'Sofular'),
  ('Şile', 'Soğullu'),
  ('Şile', 'Sortullu'),
  ('Şile', 'Şuayipli'),
  ('Şile', 'Teke'),
  ('Şile', 'Ulupelit'),
  ('Şile', 'Üvezli'),
  ('Şile', 'Yaka'),
  ('Şile', 'Yaylalı'),
  ('Şile', 'Yazımanayır'),
  ('Şile', 'Yeniköy'),
  ('Şile', 'Yeşilvadi'),
  ('Şişli', '19 Mayıs'),
  ('Şişli', 'Bozkurt'),
  ('Şişli', 'Cumhuriyet'),
  ('Şişli', 'Duatepe'),
  ('Şişli', 'Ergenekon'),
  ('Şişli', 'Esentepe'),
  ('Şişli', 'Eskişehir'),
  ('Şişli', 'Feriköy'),
  ('Şişli', 'Fulya'),
  ('Şişli', 'Gülbahar'),
  ('Şişli', 'Halaskargazi'),
  ('Şişli', 'Halide Edip Adıvar'),
  ('Şişli', 'Halil Rıfat Paşa'),
  ('Şişli', 'Harbiye'),
  ('Şişli', 'İnönü'),
  ('Şişli', 'İzzet Paşa'),
  ('Şişli', 'Kaptanpaşa'),
  ('Şişli', 'Kuştepe'),
  ('Şişli', 'Mahmut Şevket Paşa'),
  ('Şişli', 'Mecidiyeköy'),
  ('Şişli', 'Meşrutiyet'),
  ('Şişli', 'Paşa'),
  ('Şişli', 'Şişli Merkez'),
  ('Şişli', 'Teşvikiye'),
  ('Şişli', 'Yayla'),
  ('Tuzla', 'Akfırat'),
  ('Tuzla', 'Anadolu'),
  ('Tuzla', 'Aydınlı'),
  ('Tuzla', 'Aydıntepe'),
  ('Tuzla', 'Cami'),
  ('Tuzla', 'Evliya Çelebi'),
  ('Tuzla', 'Fatih'),
  ('Tuzla', 'İçmeler'),
  ('Tuzla', 'İstasyon'),
  ('Tuzla', 'Mescit'),
  ('Tuzla', 'Mimar Sinan'),
  ('Tuzla', 'Orhanlı'),
  ('Tuzla', 'Orta'),
  ('Tuzla', 'Postane'),
  ('Tuzla', 'Şifa'),
  ('Tuzla', 'Tepeören'),
  ('Tuzla', 'Yayla'),
  ('Ümraniye', 'Adem Yavuz'),
  ('Ümraniye', 'Altınşehir'),
  ('Ümraniye', 'Armağanevler'),
  ('Ümraniye', 'Aşağı Dudullu'),
  ('Ümraniye', 'Atakent'),
  ('Ümraniye', 'Atatürk'),
  ('Ümraniye', 'Cemil Meriç'),
  ('Ümraniye', 'Çakmak'),
  ('Ümraniye', 'Çamlık'),
  ('Ümraniye', 'Dumlupınar'),
  ('Ümraniye', 'Elmalıkent'),
  ('Ümraniye', 'Esenevler'),
  ('Ümraniye', 'Esenkent'),
  ('Ümraniye', 'Esenşehir'),
  ('Ümraniye', 'Fatih Sultan Mehmet'),
  ('Ümraniye', 'Finanskent'),
  ('Ümraniye', 'Hekimbaşı'),
  ('Ümraniye', 'Huzur'),
  ('Ümraniye', 'Ihlamurkuyu'),
  ('Ümraniye', 'İnkılap'),
  ('Ümraniye', 'İstiklal'),
  ('Ümraniye', 'Kazım Karabekir'),
  ('Ümraniye', 'Madenler'),
  ('Ümraniye', 'Mehmet Akif'),
  ('Ümraniye', 'Namık Kemal'),
  ('Ümraniye', 'Necip Fazıl'),
  ('Ümraniye', 'Parseller'),
  ('Ümraniye', 'Site'),
  ('Ümraniye', 'Şerifali'),
  ('Ümraniye', 'Tantavi'),
  ('Ümraniye', 'Tatlısu'),
  ('Ümraniye', 'Tepeüstü'),
  ('Ümraniye', 'Topağacı'),
  ('Ümraniye', 'Yamanevler'),
  ('Ümraniye', 'Yukarı Dudullu'),
  ('Üsküdar', 'Acıbadem'),
  ('Üsküdar', 'Ahmediye'),
  ('Üsküdar', 'Altunizade'),
  ('Üsküdar', 'Aziz Mahmut Hüdayi'),
  ('Üsküdar', 'Bahçelievler'),
  ('Üsküdar', 'Barbaros'),
  ('Üsküdar', 'Beylerbeyi'),
  ('Üsküdar', 'Bulgurlu'),
  ('Üsküdar', 'Burhaniye'),
  ('Üsküdar', 'Cumhuriyet'),
  ('Üsküdar', 'Çengelköy'),
  ('Üsküdar', 'Ferah'),
  ('Üsküdar', 'Güzeltepe'),
  ('Üsküdar', 'İcadiye'),
  ('Üsküdar', 'Kandilli'),
  ('Üsküdar', 'Kısıklı'),
  ('Üsküdar', 'Kirazlıtepe'),
  ('Üsküdar', 'Kuleli'),
  ('Üsküdar', 'Kuzguncuk'),
  ('Üsküdar', 'Küçük Çamlıca'),
  ('Üsküdar', 'Küçüksu'),
  ('Üsküdar', 'Küplüce'),
  ('Üsküdar', 'Mehmet Akif Ersoy'),
  ('Üsküdar', 'Mimar Sinan'),
  ('Üsküdar', 'Muratreis'),
  ('Üsküdar', 'Salacak'),
  ('Üsküdar', 'Selami Ali'),
  ('Üsküdar', 'Selimiye'),
  ('Üsküdar', 'Sultantepe'),
  ('Üsküdar', 'Ünalan'),
  ('Üsküdar', 'Valide-İ Atik'),
  ('Üsküdar', 'Yavuztürk'),
  ('Üsküdar', 'Zeynep Kamil'),
  ('Zeytinburnu', 'Beştelsiz'),
  ('Zeytinburnu', 'Çırpıcı'),
  ('Zeytinburnu', 'Gökalp'),
  ('Zeytinburnu', 'Kazlıçeşme'),
  ('Zeytinburnu', 'Maltepe'),
  ('Zeytinburnu', 'Merkezefendi'),
  ('Zeytinburnu', 'Nuripaşa'),
  ('Zeytinburnu', 'Seyitnizam'),
  ('Zeytinburnu', 'Sümer'),
  ('Zeytinburnu', 'Telsiz'),
  ('Zeytinburnu', 'Veliefendi'),
  ('Zeytinburnu', 'Yenidoğan'),
  ('Zeytinburnu', 'Yeşiltepe')
) as v(district_name, name) on d.name = v.district_name
on conflict (district_id, name) do nothing;
